### ISSUE TITLE
change  response in channel icdb

### ISSUE THREAD

**Issue by TranRed** [icecreamdatabase/IceCreamDataBase#106]
It should just say the same as in its own channel for now, instead of sending the user over to channelpoints_tts
 `icdbBot 📣 @[user], The TTS system is currently offline. We are looking into a replacement but this will most likely take a few weeks or longer. We are terribly sorry for the inconvenience. 󠀀 `

![grafik](https://user-images.githubusercontent.com/16636423/88440112-496d0680-ce0d-11ea-94a1-ea14a8a3a697.png)

**Comment by cineafx** [comment]
Fixed from database.
![image](https://user-images.githubusercontent.com/7873738/88453689-98488980-ce69-11ea-9129-7303b374bb2f.png)
